services:
  - type: web
    name: parking-app-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://dohaboulouiz.github.io/parking-app
      - key: CORS_ALLOWED_ORIGINS
        value: https://dohaboulouiz.github.io
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: parking-app-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: STRIPE_KEY
        sync: false

databases:
  - name: parking-app-db
    plan: free
